version = "1.3.0"

[httpd]
bind = "0.0.0.0"
port = "8001"

[protocol.unifi]
default_transcoder = "fmp4"

[protocol.unifi.server.streaming]
protocol = "ws"
bind = "0.0.0.0"
port = "8002"

[protocol.rtsp]
default_transcoder = "hls"

[protocol.rtsp.server.streaming]
protocol = "ws"
bind = "0.0.0.0"
port = "8003"

[protocol.rtsp.server.file]
protocol = "http"
bind = "0.0.0.0"
port = "8004"

[protocol.rtsp.transcoder.hls]
server  = "file"
program = "ffmpeg"
options = """-hide_banner -loglevel error -nostats \
             -re -i {input_url} -err_detect ignore_err -flags +bitexact -tune zerolatency \
             -vcodec copy -an \
             -f hls \
             -hls_time 5 -hls_list_size 3 -hls_flags delete_segments \
             {output_file}"""

[protocol.rtsp.transcoder.mpegts]
server  = "streaming"
program = "ffmpeg"
options = """-hide_banner -loglevel error -nostats \
             -re -i {input_url} -err_detect ignore_err -flags +bitexact -tune zerolatency \
             -vcodec copy -an \
             -f mpegts"""

[protocol.rtsp.transcoder.flv]
server  = "streaming"
program = "ffmpeg"
options = """-hide_banner -loglevel error -nostats \
             -re -i {input_url} -err_detect ignore_err -flags +bitexact -tune zerolatency \
             -vcodec copy -an \
             -f flv"""

[protocol.rtsp.transcoder.fmp4_1]
server  = "streaming"
program = "ffmpeg"
options = """-hide_banner -loglevel error -nostats \
             -re -i {input_url} -err_detect ignore_err -flags +bitexact -tune zerolatency \
             -vcodec copy -an
             -f mp4 \
             -movflags frag_keyframe+empty_moov+default_base_moof"""

[protocol.rtsp.transcoder.fmp4_2]
server  = "streaming"
program = "ffmpeg"
options =  """-hide_banner -loglevel error -nostats \
             -re -i {input_url} -err_detect ignore_err -flags +bitexact -tune zerolatency \
             -rtsp_transport tcp \
             -fflags nobuffer -buffer_size 100000k \
             -analyzeduration 1000000 -probesize 1000000 \
             -vcodec copy -an \
             -f mp4 \
             -movflags frag_keyframe+empty_moov+default_base_moof"""

[protocol.rtsp.transcoder.fmp4_3]
server  = "streaming"
program = "ffmpeg"
options = """-hide_banner -loglevel error -nostats \
             -re -i {input_url} -err_detect ignore_err -flags +bitexact -tune zerolatency \
             -rtsp_transport tcp \
             -fflags nobuffer -max_delay 5000000 \
             -analyzeduration 1000000 -probesize 1000000 \
             -vcodec copy -an \
             -f mp4 \
             -movflags frag_keyframe+empty_moov+default_base_moof"""


